require("dotenv").config();
const definitions = require("./definitions.ts");
const port = process.env.PORT || 3000;

const doc = {
  info: {
    version: "1.0.0",
    title: "Bus Station",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },

  host: `http://127.0.0.1:${port}`,
  basePath: "/",
  schemes: ["http"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [""],
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header", // can be "header", "query" or "cookie"
      name: "X-API-KEY", // name of the header, query parameter or cookie
      description: "any description...",
    },
  },
  definitions,
};

const outputFile = "../swagger-output.json";
const endpointsFiles = ["../index.ts"];

require("swagger-autogen")()(outputFile, endpointsFiles, doc);
